version: "3.9"
services:
  web:
    build: .
    ports:
      - "80:80"
      - "443:443"
    command: bash -c "service nginx restart && uwsgi --uid www-data -s 127.0.0.1:29000 --plugins=python3 --mount /=notes_app:app "